name: decorated_flutter
description: Common encapsulation of Flutter includes the implementation of BLoC pattern and other widget combination.
version: 0.22.0
homepage: https://github.com/yohom/decorated_flutter.git

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 国际化
  intl: ^0.16.1
  # 网络请求
  dio: ^3.0.10
  # rx
  rxdart: ^0.24.1
  # 图片加载增强
  cached_network_image: ^2.4.1
  # toast
  oktoast: ^2.3.2
  # 模态对话框增强
  modal_bottom_sheet: 1.0.0+1
  # 日志打印
  logger: ^0.9.4

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
