name: decorated_flutter
description: Common encapsulation of Flutter includes the implementation of BLoC pattern and other widget combination.
version: 0.25.0-pre.1
homepage: https://github.com/yohom/decorated_flutter.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 国际化 https://pub.flutter-io.cn/packages/intl
  intl: ^0.17.0
  # 网络请求 https://pub.flutter-io.cn/packages/dio
  dio: ^4.0.0-beta4
  # rx https://pub.flutter-io.cn/packages/rxdart
  rxdart: ^0.26.0
  # 图片加载增强 https://pub.flutter-io.cn/packages/cached_network_image
  cached_network_image: ^3.0.0-nullsafety
  # toast https://pub.flutter-io.cn/packages/oktoast
  oktoast: ^3.0.0
  # 模态对话框增强 https://pub.flutter-io.cn/packages/modal_bottom_sheet
  modal_bottom_sheet: ^2.0.0-nullsafety.1
  # 日志打印 https://pub.flutter-io.cn/packages/logger
  logger: ^1.0.0-nullsafety.0
  # 获取路径 https://pub.flutter-io.cn/packages/path_provider
  path_provider: ^2.0.1

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
